docs: typo's & structure
neow3j/neow3j-docs pull request #11
Opened 2022-09-26 11:49 UTC by ixje

Was reading the documentation and noticed some typo's. The change on the `NeoVM stack items` was discussed on Discord

2022-09-26 11:50 UTC, ixje commented on docs/neo-n3/README.md
> +The neow3j devpack is a Java library that provides the Neo-specific functionality required to write a smart contract. If
alternative "write smart contract**s**"

2022-09-26 11:51 UTC, ixje commented on docs/neo-n3/dapp_development/interacting_with_a_node.md
> +Next to the return value you can also check what notifications have been triggered by the transaction. The applications
I was expecting this as "what notifications have" or "what notification has"

2022-09-26 11:51 UTC, ixje commented on docs/neo-n3/dapp_development/interacting_with_a_node.md
> +NeoOpenWallet response = neow3j.openWallet("/path/to/wallet.json", "walletPassword").send();
this is about using the same instance as was defined at the start in the document

2022-09-27 09:11 UTC, mialbu requested changes

2022-09-27 09:11 UTC, mialbu commented on docs/neo-n3/README.md
> +The neow3j devpack is a Java library that provides the Neo-specific functionality required to write a smart contract. If
I like the alternative better.

```suggestion
The neow3j devpack is a Java library that provides the Neo-specific functionality required to write smart contracts. If
```

2022-09-27 09:14 UTC, mialbu approved these changes
Great stuff, thanks for taking the time @ixje! 💯

2022-09-27 09:14 UTC, merged